rutitle: "<gold><bold>Server Rules"

linesPerPage: 5

rules:
  - "<yellow>1. <white>Be respectful to all players and staff."
  - "<yellow>2. <white>No griefing or stealing from other players."
  - "<yellow>3. <white>No spamming or excessive use of caps in chat."
  - "<yellow>4. <white>No cheating, hacking, or using mods that give unfair advantages."
  - "<yellow>5. <white>No advertising other servers or websites."
  - "<yellow>6. <white>Keep language family-friendly in public chat."
  - "<yellow>7. <white>Do not abuse glitches or exploits. Report them to staff."
  - "<yellow>8. <white>Respect others' privacy and personal information."
  - "<yellow>9. <white>Follow staff instructions and decisions."
  - "<yellow>10. <white>Have fun and enjoy your time on the server!"