joinandleave:
  # Customize the join message
  joinMessage: |
    [<green>+</green>]%player_name% Joined.
    [<blue>Discord</blue>] Your discord
    or more if you want

  quitMessage: |
    [<red>-</red>]%player_name% Left.

# Game mode messages
gamemode:
  gmcMessage: "<green>You are now in Creative mode."
  gmsMessage: "<green>You are now in Survival mode."
  gmspMessage: "<green>You are now in Spectator mode."
  gmaMessage: "<green>You are now in Adventure mode."

tpa:
  # TPA accept/deny symbols and messages
  tpaAcceptSymbol: " ✔ "
  tpaAcceptSymbolColor: "GREEN"
  tpaAcceptHoverText: "<green>Click to accept"
  tpaDenySymbol: " ✘ "
  tpaDenySymbolColor: "RED"
  tpaDenyHoverText: "<red>Click to deny"

  # Customize the messages sent when a teleport request is accepted or denied
  tpaAccepted: "<green>Your teleport request was accepted. Teleporting to %target%."
  tpaRequestAccepted: "<green>You accepted %requester%'s teleport request."
  tpahereAccepted: "<green>Your teleport request was accepted. %target% is teleporting to you."
  tpahereRequestAccepted: "<green>You accepted %requester%'s request to teleport to them."
  tpRequestDenied: "<red>Your teleport request was denied."
  tpDenyConfirmation: "<red>You denied the teleport request."

directmessaging:
  msgUsage: "<red>Usage: /msg <player> <message>"
  replyUsage: "<red>Usage: /r <message>"
  noOneToReplyTo: "<red>You have no one to reply to."
  msgFormatSender: "[<red>me</red> <gray>-></gray> <red>%recipient%</red>] %message%"
  msgFormatRecipient: "[<red>%sender%</red> <gray>-></gray> <red>me</red>] %message%"

economy:
  playerOnly: "<red>This command can only be used by players!"
  noPermission: "<red>You don't have permission to use this command."
  playerNotFound: "<red>Player not found or not online."
  invalidAmount: "<red>Invalid amount. Please enter a positive number."
  insufficientFunds: "<red>Insufficient funds."
  balanceUsage: "<red>Usage: /balance [player]"
  balanceMessage: "<green>%player%'s balance: $%balance%"
  payUsage: "<red>Usage: /pay <player> <amount>"
  paymentSent: "<green>You sent $%amount% to %player%."
  paymentReceived: "<green>You received $%amount% from %player%."
  balTopHeader: "<gold>===== Top 10 Balances ====="
  balTopEntry: "<yellow>%position%</yellow>. %player%: <green>$%balance%"
  addMoneyUsage: "<red>Usage: /addmoney <player> <amount>"
  moneyAdded: "<green>Added $%amount% to %player%'s balance."
  moneyReceived: "<green>$%amount% has been added to your balance."
  removeMoneyUsage: "<red>Usage: /removemoney <player> <amount>"
  moneyRemoved: "<green>Removed $%amount% from %player%'s balance."
  moneyDeducted: "<green>$%amount% has been deducted from your balance."
  withdrawUsage: "<red>Usage: /withdraw <amount>"
  withdrawSuccess: "<green>You withdrew %amount%. New balance: %balance%"
  banknote:
    name: "<gold>%currency% Bank Note"
    description: "<white>Right-click to deposit %amount% into your account."
    lore:
      - "<yellow>Amount: %amount%"
      - "<gray>Right-click to deposit"
    currency: "Dollar"
    depositSuccess: "<green>Successfully deposited %amount% into your account."
    depositFailed: "<red>Failed to deposit the bank note. Please try again."

tab-menu:
  update-interval: 20 # Update interval in ticks (20 ticks = 1 second)
  header: "<gold>Welcome to <gradient:red:blue>Your Server</gradient>!"
  footer: "<gray>Players online: <green>%server_online%</green>"
  name-format: "<group_color><group_name> <white>| "#Player name is their by defult no needs for the <player> tag
  group-colors:
    default: "<gray>"
    vip: "<green>"
    admin: "<red>"
    owner: "<dark_red>"

fly:
  playerOnly: "<red>This command can only be used by players!"
  noPermission: "<red>You don't have permission to use this command."
  enabled: "<green>Flight mode enabled."
  disabled: "<red>Flight mode disabled."

home:
  # Maximum number of homes a player can set
  maxHomes: 3

  # Per-permission home limits (overrides maxHomes if set)
  # Permission nodes correspond to the ones defined in your permissions plugin
  homeLimits:
    servertools.home.limit.1: 1
    servertools.home.limit.5: 5
    servertools.home.limit.unlimited: -1  # Use -1 for unlimited homes

  # Messages
  playerOnly: "<red>This command can only be used by players!"
  noPermission: "<red>You don't have permission to use this command."
  setHome: "<green>Home '%home_name%' set!"
  teleportHome: "<green>Teleported to home '%home_name%'."
  noHomeSet: "<red>You have not set a home named '%home_name%' yet."
  homeDeleted: "<green>Your home '%home_name%' has been deleted."
  noHomeToDelete: "<red>You don't have a home named '%home_name%' to delete."
  homeLimitReached: "<red>You have reached the maximum number of homes."
  listHomes: "<green>Your homes: %homes%"
  noHomesSet: "<red>You have not set any homes yet."