name: Server-Tools
version: '2.0'
main: org.yes.ServerTools.ServerTools
description: Commands for WSN by SamTech
author: SamTech
website: https://Sam-Tech.net
api-version: '1.21'
softdepend: [Vault, PlaceholderAPI]
commands:
  #game mode shortner
  gmc:
    description: Change game mode to Creative
  gms:
    description: Change game mode to Survival
  gmsp:
    description: Change game mode to Spectator
  gma:
    description: Change game mode to Adventure
  #tpa
  tpa:
    description: Send a teleport request to a player
  tpahere:
    description: Request a player to teleport to you
  tpaccept:
    description: Accept a teleport request
  tpdeny:
    description: Deny a teleport request
  #direct message
  msg:
    description: Send a private message to a player
    usage: /<command> <player> <message>
    aliases: [ tell, w ]
  r:
    description: Reply to the last received private message
    usage: /<command> <message>
  #econ
  pay:
    description: Pay another player
    usage: /<command> <player> <amount>
  balance:
    description: Check your balance
    usage: /<command>
    aliases: [ bal ]
  withdraw:
    description: Withdraw money from your account
    usage: /<command> <amount>
  baltop:
    description: Shows top 10 player balances
    usage: /baltop
  addmoney:
    description: Adds money to a player's balance
    usage: /addmoney <player> <amount>
  removemoney:
      description: Removes money from a player's balance
      usage: /removemoney <player> <amount

permissions:
  servertools.addmoney:
    description: Allows adding money to a player's balance
    default: op
  servertools.removemoney:
    description: Allows removing money from a player's balance
    default: op