name: ServerTools
version: '3.0'
main: ServerTools.ServerTools
description: A versatile server management plugin
author: Sam
website: https://Sam-Tech.net (comming soon)
api-version: '1.21'
depend: [PlaceholderAPI]
softdepend: [Vault, LuckPerms]

commands:
  # Game mode shortener
  gmc:
    description: Change game mode to Creative
    permission: servertools.gamemode.creative
  gms:
    description: Change game mode to Survival
    permission: servertools.gamemode.survival
  gmsp:
    description: Change game mode to Spectator
    permission: servertools.gamemode.spectator
  gma:
    description: Change game mode to Adventure
    permission: servertools.gamemode.adventure
  # TPA
  tpa:
    description: Send a teleport request to a player
    permission: servertools.tpa.send
  tpahere:
    description: Request a player to teleport to you
    permission: servertools.tpa.sendhere
  tpaccept:
    description: Accept a teleport request
    permission: servertools.tpa.accept
  tpdeny:
    description: Deny a teleport request
    permission: servertools.tpa.deny
  # Direct message
  msg:
    description: Send a private message to a player
    usage: /<command> <player> <message>
    aliases: [tell, w]
    permission: servertools.message.send
  r:
    description: Reply to the last received private message
    usage: /<command> <message>
    permission: servertools.message.reply
  # Economy
  pay:
    description: Pay another player
    usage: /<command> <player> <amount>
    permission: servertools.economy.pay
  balance:
    description: Check your balance
    usage: /<command>
    aliases: [bal]
    permission: servertools.economy.balance
  withdraw:
    description: Withdraw money from your account
    usage: /<command> <amount>
    permission: servertools.economy.withdraw
  baltop:
    description: Shows top 10 player balances
    usage: /baltop
    permission: servertools.economy.baltop
  addmoney:
    description: Adds money to a player's balance
    usage: /addmoney <player> <amount>
    permission: servertools.economy.addmoney
  removemoney:
    description: Removes money from a player's balance
    usage: /removemoney <player> <amount>
    permission: servertools.economy.removemoney
  # Fly command
  fly:
    description: Toggle flight mode
    usage: /<command>
    aliases: [togglefly]
    permission: servertools.fly
  #homes
  sethome:
    description: Set a home location
    usage: /<command> [homeName]
    permission: servertools.home.sethome
  home:
    description: Teleport to a home
    usage: /<command> [homeName]
    permission: servertools.home.home
  delhome:
    description: Delete a home
    usage: /<command> [homeName]
    permission: servertools.home.delhome
  homes:
    description: List your homes
    usage: /<command>
    aliases: [listhomes]
    permission: servertools.home.homes
  #help
  help:
    description: Shows the help menu
    usage: /<command> [page]
    permission: servertools.help
  #rules
  rules:
    description: View the server rules
    usage: /<command> [page]
    permission: servertools.rules
  #afk
  afk:
    description: Toggle AFK status.
    usage: /afk
    permission: servertools.afk

#--------------------------------------------------------------------------------Perms v  Commands^
permissions:
  #gamemodes
  servertools.gamemode.*:
    description: Allows access to all gamemode commands
    children:
      servertools.gamemode.creative: true
      servertools.gamemode.survival: true
      servertools.gamemode.spectator: true
      servertools.gamemode.adventure: true
  servertools.gamemode.creative:
    description: Allows changing to creative mode
    default: op
  servertools.gamemode.survival:
    description: Allows changing to survival mode
    default: op
  servertools.gamemode.spectator:
    description: Allows changing to spectator mode
    default: op
  servertools.gamemode.adventure:
    description: Allows changing to adventure mode
    default: op
  #tpa
  servertools.tpa.*:
    description: Allows access to all TPA commands
    children:
      servertools.tpa.send: true
      servertools.tpa.sendhere: true
      servertools.tpa.accept: true
      servertools.tpa.deny: true
  servertools.tpa.send:
    description: Allows sending teleport requests
    default: true
  servertools.tpa.sendhere:
    description: Allows sending teleport-here requests
    default: true
  servertools.tpa.accept:
    description: Allows accepting teleport requests
    default: true
  servertools.tpa.deny:
    description: Allows denying teleport requests
    default: true
  #direct Message
  servertools.message.*:
    description: Allows access to all messaging commands
    children:
      servertools.message.send: true
      servertools.message.reply: true
  servertools.message.send:
    description: Allows sending private messages
    default: true
  servertools.message.reply:
    description: Allows replying to private messages
    default: true
  #economy
  servertools.economy.*:
    description: Allows access to all economy commands
    children:
      servertools.economy.pay: true
      servertools.economy.balance: true
      servertools.economy.withdraw: true
      servertools.economy.baltop: true
      servertools.economy.addmoney: true
      servertools.economy.removemoney: true
  servertools.economy.pay:
    description: Allows paying other players
    default: true
  servertools.economy.balance:
    description: Allows checking balance
    default: true
  servertools.economy.withdraw:
    description: Allows withdrawing money
    default: true
  servertools.economy.baltop:
    description: Allows viewing top balances
    default: true
  servertools.economy.addmoney:
    description: Allows adding money to a player's balance
    default: op
  servertools.economy.removemoney:
    description: Allows removing money from a player's balance
    default: op
  #fly
  servertools.fly:
    description: Allows toggling flight mode
    default: op
  #homes
  servertools.home.*:
    description: Allows access to all home commands
    children:
      servertools.home.sethome: true
      servertools.home.home: true
      servertools.home.delhome: true
      servertools.home.homes: true
  servertools.home.sethome:
    description: Allows setting homes
    default: true
  servertools.home.home:
    description: Allows teleporting to homes
    default: true
  servertools.home.delhome:
    description: Allows deleting homes
    default: true
  servertools.home.homes:
    description: Allows listing homes
    default: true

  # Per-permission home limits
  servertools.home.limit.1:
    description: Allows setting up to 1 home
    default: false
  servertools.home.limit.5:
    description: Allows setting up to 5 homes
    default: false
  servertools.home.limit.unlimited:
    description: Allows setting unlimited homes
    default: false
  # help
  servertools.help:
    description: Allows access to the /help command
    default: true
  # Rules
  servertools.rules:
    description: Allows access to the /rules command
    default: true

  #akf
  servertools.afk:
    description: Allows use of the AFK command
    default: true
  #Reload